server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:./data/persons/sampledata;OLD_INFORMATION_SCHEMA=TRUE
    username: sa
    password: sa
eureka:
  client:
    eureka-service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true