server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:./data/persons/sampledata;OLD_INFORMATION_SCHEMA=TRUE
    username: sa
    password: sa
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false

springdoc:
  swagger-ui: path=/swagger-ui.html